apiVersion: batch/v1
kind: Job
metadata:
  name: benchmark-run
  namespace: llm-d-benchmark
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: llm-d-benchmark
    spec:
      serviceAccountName: benchmark-runner
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: evaluation
        # TODO: UPDATE IMAGE
        image: quay.io/sallyom/llm-d-benchmark:quickstart
        imagePullPolicy: Always
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        command: ["sh"]
        args: ["-c", "ln -sf /workspace/config/llmdbench_workload.yaml /workspace/llmdbench_workload.yaml && python3 /workspace/workload/harnesses/llm-d-benchmark.py"]
        env:
        - name: LLMDBENCH_HARNESS_STACK_ENDPOINT_URL
          value: "http://llm-d-inference-gateway-istio.llm-d.svc.cluster.local:80"
        - name: LLMDBENCH_HARNESS_STACK_NAME
          value: "llm-d-qwen-0-6b"
        - name: LLMDBENCH_HARNESS_STACK_TYPE
          value: "llm-d"
        - name: LLMDBENCH_FMPERF_REPETITION
          value: "1"
        - name: LLMDBENCH_HARNESS_NAMESPACE
          value: "llm-d-benchmark"
        - name: LLMDBENCH_HARNESS_WORKLOAD_FILE
          value: "llmdbench_workload.yaml"
        envFrom:
        - configMapRef:
            name: benchmark-env
        volumeMounts:
        - name: results
          mountPath: /requests
        - name: workload-file
          mountPath: /workspace/config
          readOnly: true
      volumes:
      - name: results
        persistentVolumeClaim:
          claimName: benchmark-results-pvc
      - name: workload-file
        configMap:
          name: benchmark-workload-config
      restartPolicy: Never
