apiVersion: v1
kind: Service
metadata:
  name: inference-gateway
  namespace: llm-d-benchmark
spec:
  type: ExternalName
  externalName: llm-d-inference-gateway-istio.llm-d.svc.cluster.local
  ports:
  - port: 80
    targetPort: 80 